replicaCount: 2

minReadySeconds: 5

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/presence
    tag: ""

  resources:
    requests:
      cpu: 0.1
      memory: 50Mi

  websocket:
    ping_interval: 30s
    pong_expiration_interval: 5s
    authentication_timeout: 5s
    wait_before_close_connection: 10s

migrations:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/presence-migration
    tag: ""

  resources:
    limits:
      cpu: 0.1
      memory: 100Mi
    requests:
      cpu: 0.1
      memory: 100Mi

env:
  RUST_LOG: warn,presence=info,svc_utils=info,svc_utils::metrics=warn
  CACHE_ENABLED: 1
  CACHE_POOL_SIZE: 50
  CACHE_POOL_IDLE_SIZE: 5
  CACHE_POOL_TIMEOUT: 5
  CACHE_EXPIRATION_TIME: 300
  DATABASE_POOL_SIZE: 10
  DATABASE_POOL_IDLE_SIZE: 10
  DATABASE_POOL_TIMEOUT: 5
  DATABASE_POOL_MAX_LIFETIME: 43200

clusterService:
  ports:
    http: 8080
    metrics: 8888

tls:
  secretName: tls-certificates
