version: '3.8'
services:
  db:
    image: postgres:12.9-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  nats:
    image: nats:latest
    ports:
      - '4222:4222'
    command: '-js -c /etc/nats-config/nats.conf'
    volumes:
      - ./nats/nats.conf:/etc/nats-config/nats.conf

volumes:
  postgres:
