id = "presence.dev.svc.example.org"
listener_address = "0.0.0.0:3000"
svc_audience = "svc.example.org"

[websocket]
ping_interval = "30s"
pong_expiration_interval = "5s"
authentication_timeout = "5s"
check_old_connection_interval = "5s"

[authn."svc.example.org"]
audience = ["dev.svc.example.org"]
algorithm = "ES256"
key = "data/keys/svc.public_key.p8.der.sample"

[authz."svc.example.org"]
type = "local"
trusted = ["dev.svc.example.org"]
