[package]
name = "presence"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dotenv = "0.15.0"
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" , "postgres", "offline", "uuid" ] }
tokio = { version = "1.16", features = ["full"] }

[dev-dependencies]
testcontainers = "0.12"
