listener_address = "0.0.0.0:3000"

[authn."dev.svc.example.org"]
audience = ["dev.svc.example.org"]
algorithm = "ES256"
key = "data/keys/svc.public_key.p8.der.sample"

[websocket]
ping_interval = 30
pong_expiration_interval = 5
authentication_timeout = 5
