apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: foxford/presence-migration
      docker:
        dockerfile: docker/migration.dockerfile
    - image: foxford/presence
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: presence
        chartPath: chart
        artifactOverrides:
          app.image: foxford/presence
          migrations.image: foxford/presence-migration
        imageStrategy:
          helm: {}
        valuesFiles:
          - deploy/values.yaml
