apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "presence.labels" . | nindent 4 }}
  name: {{ include "presence.fullname" . }}-app
data:
  App.toml: |
    {{- $id := list (include "presence.name" . ) .Values.app.svc.audience | compact | join "." }}
    id = {{ $id | quote }}
    listener_address = "0.0.0.0:8080"
    internal_listener_address = "0.0.0.0:8081"
    metrics_listener_address = "0.0.0.0:8888"
    svc_audience = {{ $.Values.app.svc.audience | quote }}

    [websocket]
    ping_interval = {{ .Values.app.websocket.ping_interval | quote }}
    pong_expiration_interval = {{ .Values.app.websocket.pong_expiration_interval | quote }}
    authentication_timeout = {{ .Values.app.websocket.authentication_timeout | quote }}
    wait_before_close_connection = {{ .Values.app.websocket.wait_before_close_connection | quote }}

    [sentry]
    dsn = {{ .Values.sentry.dsn | quote }}
    environment = {{ .Release.Namespace | quote }}

    {{- println "" }}

    {{- with .Values.app.svc }}
    ##
    ## SVC
    ##
    [authn.{{ .audience | quote }}]
    audience = [{{ .audience | quote }}]
    algorithm = "ES256"
    key = {{ .authn.key | quote }}

    {{- println "" }}
    [authz.{{ .audience | quote }}]
    type = {{ .authz.type | quote }}
    {{- if eq "local" .authz.type }}
    trusted = [
      {{- range $account_label := .authz.trusted }}
        {{ (list $account_label $.Values.app.svc.audience) | compact | join "." | quote }},
      {{- end }}
    ]
    {{- if eq "localwhitelist" .authz.type }}
    [[authz.{{ $.Values.app.svc.audience | quote }}.records]]
    {{- range $record := .authz.records }}
    subject_account_id = {{ get $record "subject_account_id" | quote }}
    object = [
      {{- range $o := get $record "object" }}
      {{ $o | quote }},
      {{- end}}
    ]
    action = {{ get $record "action" | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}

    {{- println "" }}

    {{- range .Values.app.audiences }}
    ##
    ## {{ .audience }}
    ##
    {{- $audience := .audience }}
    {{- $tenantServiceAudience := include "presence.tenantServiceAudience" .audience }}
    {{- $tenantUserAudience := include "presence.tenantUserAudience" .audience }}
    {{- $tenantObjectAudience := include "presence.tenantObjectAudience" (list $.Release.Namespace .audience) }}
    {{- with "authn" | get . }}
    [authn.{{ list "iam" $tenantServiceAudience | join "." | quote }}]
    audience = [{{ $tenantServiceAudience | quote }}, {{ $tenantUserAudience | quote }}]
    algorithm = "ES256"
    key = {{ "key" | get . | quote }}
    {{- end }}

    {{- println "" }}

    {{- with "authz" | get . }}
    [authz.{{ $audience | quote }}]
    type = {{ .type | quote }}
    {{- if eq "http" .type }}
    {{- $defaultAuthzUrl := list "http://dispatcher-cluster:8080/api/v1/authz/" $tenantObjectAudience | join "" }}
    uri = {{ default $defaultAuthzUrl .uri | quote }}
    algorithm = {{ default "ES256" .algorithm | quote }}
    key = {{ default "data/keys/svc.private_key.p8.der" .key | quote }}
    user_agent = {{ default $id .user_agent | quote }}
    max_retries = {{ default 3 .max_retries }}
    {{- end }}
    {{- if eq "local" .type }}
    trusted = [
      {{- range $account_label := .trusted }}
        {{ (list $account_label $.Values.app.svc.audience) | compact | join "." | quote }},
      {{- end }}
    ]
    {{- end }}
    {{- if eq "localwhitelist" .type }}
    [[authz.{{ $tenantObjectAudience | quote }}.records]]
    {{- range $record := .records }}
    subject_account_id = {{ get $record "subject_account_id" | quote }}
    object = [
      {{- range $o := get $record "object" }}
      {{ $o | quote }},
      {{- end}}
    ]
    action = {{ get $record "action" | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- println "" }}
    {{- end }}

    {{- with .Values.nats }}
    {{- println "" }}
    [nats]
    url = {{ .url | quote }}
    creds = {{ .creds | quote }}
    subscribe_ephemeral.stream = {{ .subscribe_ephemeral.stream | quote }}
    {{- end }}
