apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "presence.fullname" . }}
  labels:
    {{- include "presence.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      {{- include "presence.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/app-cm: {{ include (print $.Template.BasePath "/app-cm.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "presence.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "presence.name" . }}
      imagePullSecrets:
        - name: regcred
      initContainers:
        - image: "{{ .Values.networkTester.image.repository }}:{{ .Values.networkTester.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: network-tester
        - name: init-{{ .Chart.Name }}-migration
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Values.app.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "presence.name" . }}-credentials
                  key: database_url
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: "CACHE_URL"
              valueFrom:
                secretKeyRef:
                  name: redis-{{ include "presence.name" . }}-credentials
                  key: CACHE_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "presence.name" . }}-credentials
                  key: database_url
            - name: APP_AGENT_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
            {{- with .Values.app.svc }}
            {{- $audience := .audience }}
            {{- range $secret, $mounts := .credentials }}
            {{- range $mounts }}
            - name: {{ include "presence.volumeMountName" (list $audience $secret) }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.app.audiences }}
            {{- $audience := .audience }}
            {{- range $secret, $mounts := .credentials }}
            {{- range $mounts }}
            - name: {{ include "presence.volumeMountName" (list $audience $secret) }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.clusterService.ports.http }}
            failureThreshold: 10
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "{{ .Values.preStopSleepSeconds }}"]
      volumes:
        - name: config
          configMap:
            name: {{ include "presence.fullname" . }}-app
        {{- with .Values.app.svc }}
        {{- $audience := .audience }}
        {{- range $secret, $mounts := .credentials }}
        - name: {{ include "presence.volumeMountName" (list $audience $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
        {{- range .Values.app.audiences }}
        {{- $audience := .audience }}
        {{- range $secret, $mounts := .credentials }}
        - name: {{ include "presence.volumeMountName" (list $audience $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
