apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "presence.name" . }}-pdb
  labels:
    {{- include "presence.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "presence.selectorLabels" . | nindent 6 }}
