kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "presence.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "presence.name" . }}
roleRef:
  kind: Role
  name: {{ include "presence.name" . }}
  apiGroup: rbac.authorization.k8s.io
