apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "presence.fullname" . }}
  labels:
  {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: {{ .Chart.Name }}
  selector:
    matchLabels:
      {{- include "presence.selectorLabels" . | nindent 6 }}
