name: Check
on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo fmt --all --check
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo build --release --all-features
      - run: cargo test --all-features --verbose
        env:
          RUST_BACKTRACE: 1

  dotenv-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review
          fail_on_error: true
