name: Deploy

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Select cluster'
        required: false
        default: 'dev'
      namespace:
        type: choice
        description: 'Select namespace'
        options:
        - s01-classroom-foxford
      version:
        description: 'Commit/tag/branch'
        required: false
        default: 'master'

jobs:
  deploy:
    uses: foxford/reusable-workflows/.github/workflows/deploy-via-flux.yml@master
    with:
      cluster: ${{ inputs.cluster }}
      namespace: ${{ inputs.namespace }}
      version: ${{ inputs.version }}
    secrets:
      kube_config_base64: ${{ secrets.KUBE_CONFIG_DEV_BASE64 }}
      gh_token: ${{ secrets._GITHUB_TOKEN }}

